/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  CarConfig,
  CarModelId,
  CarCategory,
  CarStats,
  CarCustomization,
  CarUpgrades,
  PlayerRaceProfile,
  CharacterId,
} from '../../types';

export const CAR_CATALOG: CarConfig[] = [
  {
    id: 'roadster_883_3d',
    name: 'Harley-Davidson Sportster 883',
    subTitle: 'Cruiser / Roadster Motorcycle',
    category: 'motorcycle',
    description:
      'Mẫu 883 có kiểu dáng thuộc dòng Harley-Davidson Sportster. FBX không chứa metadata hãng chính thức, nên tên hãng được nhận dạng theo tên 883 và kiểu dáng; camera được chuẩn hóa riêng cho xe hai bánh.',
    baseStats: {
      topSpeed: 86,
      acceleration: 91,
      handling: 88,
      drift: 70,
      nitro: 86,
      braking: 84,
    },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#20242b',
    specialAura: '🏍️ Harley-Davidson Sportster–style 883',
  },
  {
    id: 'vespa_studio_3d',
    name: 'Piaggio Vespa 125',
    subTitle: 'Classic Italian Scooter',
    category: 'motorcycle',
    description:
      'Scooter cổ điển Piaggio Vespa 125; FBX có node logo_vespa125. Model đã được tối ưu dung lượng; PC dùng model thật, TV/Mi Box và điện thoại dùng fallback nhẹ để tránh khựng khi parse nhiều mesh.',
    baseStats: {
      topSpeed: 68,
      acceleration: 79,
      handling: 92,
      drift: 66,
      nitro: 73,
      braking: 91,
    },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#d9e8e6',
    specialAura: '🛵 Piaggio Vespa 125',
  },
  {
    id: 'canis_mesa_3d',
    name: 'Canis Mesa 4×4',
    subTitle: 'Off-Road SUV · Jeep Wrangler–style',
    category: 'suv_perf',
    description:
      'FBX xác nhận tên Canis Mesa. Đây là mẫu SUV địa hình hư cấu kiểu Jeep Wrangler; không gắn nhãn Jeep chính thức vì file không có metadata Jeep. PC/TV ưu tiên FBX thật, điện thoại yếu dùng fallback.',
    baseStats: {
      topSpeed: 76,
      acceleration: 79,
      handling: 82,
      drift: 76,
      nitro: 80,
      braking: 85,
    },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#6b7a4a',
    specialAura: '🏜️ Canis Mesa · Wrangler-style 4×4',
  },
  {
    id: 'v12_sv_3d',
    name: 'Lamborghini Murciélago LP 670-4 SV',
    subTitle: 'Italian V12 Supercar',
    category: 'supercar',
    description:
      'FBX chứa đường dẫn vật liệu Lamborghini_Murcielago_LP670-4_SV, xác nhận mẫu Lamborghini Murciélago LP 670-4 SuperVeloce. PC dùng model thật; TV/Mi Box và mobile dùng fallback nhẹ.',
    baseStats: {
      topSpeed: 97,
      acceleration: 95,
      handling: 91,
      drift: 89,
      nitro: 96,
      braking: 94,
    },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#f2c300',
    specialAura: '⚡ Lamborghini V12 SuperVeloce',
  },

  {
    id: 's14_sport_3d',
    name: 'Nissan Silvia S14',
    subTitle: 'JDM Sports / Drift Coupe',
    category: 'jdm',
    description:
      'Coupe S14 có hình dáng/tên model phù hợp Nissan Silvia S14. FBX không chứa metadata Nissan chính thức, nên nhận dạng hãng dựa trên tên S14 và kiểu dáng. Bánh giữ tĩnh khi hierarchy không đủ an toàn.',
    baseStats: { topSpeed: 88, acceleration: 86, handling: 84, drift: 91, nitro: 85, braking: 83 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#8b1018',
    specialAura: '🏁 Nissan Silvia S14 · JDM Drift',
  },
  {
    id: 'rescue_truck_hauler_3d',
    name: 'International 4400LP Expeditor',
    subTitle: 'Fire Rescue Hauler · Heavy Truck & Trailer',
    category: 'suv_perf',
    description:
      'FBX có node 2008 INTERNATIONAL 4400LP Expeditor và Fire Rescue Smart Truck Hauler, xác nhận đầu kéo International 4400LP Expeditor kèm moóc cứu hộ nhiều trục. Desktop dùng FBX thật; thiết bị khác dùng fallback.',
    baseStats: { topSpeed: 60, acceleration: 52, handling: 48, drift: 35, nitro: 58, braking: 74 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#f3f4f6',
    specialAura: '🚛 International 4400LP Fire Rescue',
  },
  {
    id: 'xedap_city_3d',
    name: 'Mamachari City Bicycle',
    subTitle: 'Japanese Step-Through City Bicycle',
    category: 'motorcycle',
    description:
      'FBX có node mamachari_dxf, xác nhận loại xe đạp thành phố Nhật kiểu Mamachari/step-through. Không tìm thấy metadata hãng sản xuất, nên không gắn thương hiệu giả. Desktop dùng FBX thật.',
    baseStats: { topSpeed: 42, acceleration: 66, handling: 95, drift: 45, nitro: 52, braking: 88 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#d7924f',
    specialAura: '🚲 Mamachari · Japanese City Bike',
  },
  {
    id: 'capybara_parade_3d',
    name: 'Capybara Parade XL',
    subTitle: 'Lowpoly Meme Racer · Capybara Caravan',
    category: 'mascot_special',
    description:
      'Model capybara lowpoly vui nhộn được bổ sung cho Gara, Gương Ma Thuật và Đua Xe. Scale được tăng lớn để dễ nhìn; đầu xoay theo hướng đua để tạo cảm giác hài hước nhưng vẫn rõ ràng.',
    baseStats: {
      topSpeed: 74,
      acceleration: 77,
      handling: 81,
      drift: 68,
      nitro: 72,
      braking: 80,
    },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#b78652',
    mascotOwner: 'bara',
    specialAura: '🦫 Capybara Parade · meme racer khổng lồ',
  },
  {
    id: 'police_car_3d',
    name: 'Police Patrol 3D',
    subTitle: 'Xe cảnh sát đặc biệt',
    category: 'sport',
    description: 'FBX xe cảnh sát nhẹ với 4 bánh tách riêng. Dùng được trong Garage và đua xe; vẫn giữ bản cảnh quan ở City Night.',
    baseStats: { topSpeed: 82, acceleration: 84, handling: 88, drift: 72, nitro: 82, braking: 92 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#f8fafc',
    specialAura: '🚓 Police Patrol',
  },
  {
    id: 'police_motorcycle_3d',
    name: 'Police Motorcycle 3D',
    subTitle: 'Mô tô cảnh sát',
    category: 'motorcycle',
    description: 'Mô tô cảnh sát FBX nhẹ, phù hợp đua xe trên điện thoại/TV/PC. Bánh giữ tĩnh khi pivot không đủ an toàn.',
    baseStats: { topSpeed: 86, acceleration: 91, handling: 92, drift: 71, nitro: 86, braking: 91 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#f8fafc',
    specialAura: '🏍️ Police Motorcycle',
  },
  {
    id: 'ambulance_3d',
    name: 'Ambulance Rescue 3D',
    subTitle: 'Xe cứu thương',
    category: 'suv_perf',
    description: 'Xe cứu thương FBX nhẹ với bốn cụm lốp rõ ràng. Có thể chọn làm xe đua đặc biệt và vẫn xuất hiện như cảnh quan.',
    baseStats: { topSpeed: 72, acceleration: 70, handling: 74, drift: 48, nitro: 72, braking: 90 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#f8fafc',
    specialAura: '🚑 Ambulance Rescue',
  },
  {
    id: 'tank_racer_3d',
    name: 'Battle Tank 3D',
    subTitle: 'Xe tăng đặc biệt',
    category: 'mascot_special',
    description: 'Xe tăng FBX được dùng như xe đua vui nhộn. TV/PC ưu tiên model thật; thiết bị yếu có fallback an toàn.',
    baseStats: { topSpeed: 52, acceleration: 48, handling: 55, drift: 30, nitro: 60, braking: 96 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#66754a',
    specialAura: '🪖 Tank Racer',
  },
  {
    id: 'helicopter_racer_3d',
    name: 'Helicopter Racer 3D',
    subTitle: 'Trực thăng bay thấp',
    category: 'mascot_special',
    description: 'Trực thăng FBX nhẹ bay thấp theo đường đua. Đây là chế độ vui nhộn, không mô phỏng vật lý trực thăng thật.',
    baseStats: { topSpeed: 90, acceleration: 88, handling: 86, drift: 40, nitro: 90, braking: 80 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#64748b',
    specialAura: '🚁 Helicopter Racer',
  },
  {
    id: 'dodge_wc51_3d',
    name: 'Dodge WC-51 3D',
    subTitle: 'Military Utility Truck',
    category: 'suv_perf',
    description: 'Dodge WC-51 FBX nặng hơn, chỉ ưu tiên model thật trên PC để tránh lag trên điện thoại/TV.',
    baseStats: { topSpeed: 64, acceleration: 58, handling: 62, drift: 42, nitro: 64, braking: 82 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#596348',
    specialAura: '🚙 Dodge WC-51',
  },
  {
    id: 'spider_racer_3d',
    name: 'Spider Hero Racer',
    subTitle: 'Nhân vật Nhện FBX',
    category: 'mascot_special',
    description: 'Nhân vật Nhện FBX nhẹ được gắn vào đua xe theo yêu cầu. Model hiện chưa có skeleton nên chạy bằng chuyển động toàn thân.',
    baseStats: { topSpeed: 88, acceleration: 94, handling: 95, drift: 82, nitro: 90, braking: 88 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#dc2626',
    specialAura: '🕷️ Spider Racer',
  },
  {
    id: 'robot19_racer_3d',
    name: 'Robot 19 Racer',
    subTitle: 'Robot FBX nhẹ',
    category: 'mascot_special',
    description: 'Robot 19 được gắn trực tiếp vào Garage/đua xe; dùng model thật trên các thiết bị đủ khả năng.',
    baseStats: { topSpeed: 84, acceleration: 86, handling: 88, drift: 68, nitro: 88, braking: 88 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#94a3b8',
    specialAura: '🤖 Robot 19',
  },
  {
    id: 'robot4_racer_3d',
    name: 'Robot 4 Racer',
    subTitle: 'Robot chiến đấu 3D',
    category: 'mascot_special',
    description: 'Robot 4 có nhiều mesh, ưu tiên TV/PC; điện thoại yếu dùng fallback để giữ FPS.',
    baseStats: { topSpeed: 86, acceleration: 84, handling: 82, drift: 65, nitro: 90, braking: 90 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#64748b',
    specialAura: '🤖 Robot 4',
  },
  {
    id: 'prime1_racer_3d',
    name: 'Prime 1 Racer',
    subTitle: 'Robot Prime 3D',
    category: 'mascot_special',
    description: 'Prime 1 FBX khá nặng, model thật được ưu tiên trên PC; thiết bị khác dùng fallback.',
    baseStats: { topSpeed: 91, acceleration: 87, handling: 82, drift: 70, nitro: 94, braking: 89 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#334155',
    specialAura: '🤖 Prime Racer',
  },
  {
    id: 'ironman_mark3_racer_3d',
    name: 'Iron Man Mark III Racer',
    subTitle: 'Armor Racer 3D',
    category: 'mascot_special',
    description: 'Iron Man Mark III FBX rất nặng và nhiều mesh; chỉ dùng model thật trên PC để tránh parse chậm trên TV/mobile.',
    baseStats: { topSpeed: 95, acceleration: 93, handling: 88, drift: 75, nitro: 98, braking: 92 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#b91c1c',
    specialAura: '🦾 Mark III Armor',
  },
  {
    id: 'zora_nao_racer_3d',
    name: 'Zora Nao Robot Racer',
    subTitle: 'Humanoid Robot 3D',
    category: 'mascot_special',
    description: 'Zora Nao Robot có nhiều nhóm tay/chân nhưng chưa xác nhận skin rig; model thật chỉ bật trên PC.',
    baseStats: { topSpeed: 80, acceleration: 82, handling: 92, drift: 66, nitro: 82, braking: 92 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#e2e8f0',
    specialAura: '🤖 Zora Nao',
  },
  {
    id: 'mark6_racer_3d',
    name: 'Armor Mark Racer',
    subTitle: 'Mark Armor FBX',
    category: 'mascot_special',
    description: 'Bộ giáp Mark FBX được đưa vào Garage/đua xe. Metadata nguồn có tên Mark II ở một số node nên giữ tên hiển thị trung tính.',
    baseStats: { topSpeed: 92, acceleration: 91, handling: 86, drift: 74, nitro: 95, braking: 91 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#b91c1c',
    specialAura: '🦾 Armor Racer',
  },
  {
    id: 'hulk_racer_3d',
    name: 'Hulk Racer 3D',
    subTitle: 'Nhân vật sức mạnh',
    category: 'mascot_special',
    description: 'Hulk FBX được đưa vào đua xe dạng nhân vật tĩnh chuyển động theo root.',
    baseStats: { topSpeed: 75, acceleration: 79, handling: 70, drift: 54, nitro: 76, braking: 96 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#4d7c0f',
    specialAura: '💪 Hulk Racer',
  },
  {
    id: 'captain_racer_3d',
    name: 'Captain Hero Racer',
    subTitle: 'Hero FBX',
    category: 'mascot_special',
    description: 'Nhân vật Captain FBX được thêm vào Garage/đua xe; chưa có skeleton nên chuyển động toàn model.',
    baseStats: { topSpeed: 82, acceleration: 85, handling: 88, drift: 68, nitro: 84, braking: 90 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#1d4ed8',
    specialAura: '🛡️ Captain Racer',
  },
  {
    id: 'knut_racer_3d',
    name: 'Knut Racer 3D',
    subTitle: 'Nhân vật vui nhộn',
    category: 'mascot_special',
    description: 'Knut FBX nhẹ được thêm vào Garage/đua xe dạng mascot.',
    baseStats: { topSpeed: 74, acceleration: 80, handling: 91, drift: 64, nitro: 76, braking: 88 },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#d6b59c',
    specialAura: '🧣 Knut Racer',
  },
  {
    id: 'us_soldier_racer_3d',
    name: 'US Soldier Racer',
    subTitle: 'Nhân vật lính FBX',
    category: 'mascot_special',
    description: 'Nhân vật lính FBX nhẹ được đưa vào Garage/đua xe dạng chuyển động toàn model.',
    baseStats: { topSpeed: 80, acceleration: 82, handling: 86, drift: 62, nitro: 80, braking: 90 },
    unlockCostStars: 0, unlockCostDiamonds: 0, isUnlockedByDefault: true,
    defaultColor: '#556b4f', specialAura: '🪖 Soldier Racer',
  },
  {
    id: 'human_racer_3d',
    name: 'Human Racer 3D',
    subTitle: 'Người mẫu FBX',
    category: 'mascot_special',
    description: 'Model người FBX nhẹ được đưa vào Garage/đua xe. Chưa có skeleton nên chuyển động toàn thân theo root.',
    baseStats: { topSpeed: 78, acceleration: 84, handling: 88, drift: 64, nitro: 78, braking: 88 },
    unlockCostStars: 0, unlockCostDiamonds: 0, isUnlockedByDefault: true,
    defaultColor: '#c9a38f', specialAura: '🧍 Human Racer',
  },
  {
    id: 'drag_driver_racer_3d',
    name: 'Drag Driver Racer',
    subTitle: 'Driver FBX',
    category: 'mascot_special',
    description: 'Model Drag Driver được đưa vào Garage/đua xe như một nhân vật đặc biệt; không giả chuyển động tay chân khi chưa có rig.',
    baseStats: { topSpeed: 84, acceleration: 88, handling: 86, drift: 70, nitro: 84, braking: 88 },
    unlockCostStars: 0, unlockCostDiamonds: 0, isUnlockedByDefault: true,
    defaultColor: '#64748b', specialAura: '🏁 Drag Driver',
  },
  {
    id: 'bara_gt',
    name: 'BARA GT',
    subTitle: 'Chiến Mã Capybara Huyền Thoại',
    category: 'mascot_special',
    description:
      'Siêu xe đặc quyền của Bara với động cơ bền bỉ, phong cách ấm áp, tăng tốc mượt mà và khả năng ôm cua cực chuẩn.',
    baseStats: {
      topSpeed: 82,
      acceleration: 85,
      handling: 88,
      drift: 80,
      nitro: 84,
      braking: 86,
    },
    unlockCostStars: 0,
    unlockCostDiamonds: 0,
    isUnlockedByDefault: true,
    defaultColor: '#c2884a',
    mascotOwner: 'bara',
    specialAura: '🌟 Hào quang Capybara thảnh thơi',
  },
  {
    id: 'ap_r1',
    name: 'AP-R1 TUNER',
    subTitle: 'JDM Street Racer',
    category: 'jdm',
    description:
      'Phong cách xe đua đường phố thể thao Nhật Bản. Thân xe khí động học nhẹ, chuyên gia ôm cua và drift khói lốp rực lửa.',
    baseStats: {
      topSpeed: 80,
      acceleration: 82,
      handling: 90,
      drift: 92,
      nitro: 78,
      braking: 85,
    },
    unlockCostStars: 15,
    unlockCostDiamonds: 5,
    isUnlockedByDefault: true,
    defaultColor: '#ef4444',
    specialAura: '🔥 Khói lốp Drift cuồng nhiệt',
  },
  {
    id: 'may_cloud_gt',
    name: 'MÂY CLOUD GT',
    subTitle: 'Cơn Lốc Bông Gòn Bồng Bềnh',
    category: 'mascot_special',
    description:
      'Thiết kế mềm mại như mây trắng trời xanh của bé Mây. Lướt êm ái trên mọi cung đường với hệ thống treo khí nén kỳ diệu.',
    baseStats: {
      topSpeed: 78,
      acceleration: 88,
      handling: 92,
      drift: 84,
      nitro: 86,
      braking: 90,
    },
    unlockCostStars: 20,
    unlockCostDiamonds: 8,
    isUnlockedByDefault: false,
    defaultColor: '#38bdf8',
    mascotOwner: 'may',
    specialAura: '☁️ Vệt mây mềm mại lướt gió',
  },
  {
    id: 'ap_gt',
    name: 'AP-GT EURO',
    subTitle: 'European Grand Tourer',
    category: 'euro_sport',
    description:
      'Đẳng cấp xe thể thao châu Âu sang trọng. Tốc độ ổn định trên đường trường với động cơ V8 gầm vang dũng mãnh.',
    baseStats: {
      topSpeed: 86,
      acceleration: 84,
      handling: 82,
      drift: 78,
      nitro: 85,
      braking: 88,
    },
    unlockCostStars: 30,
    unlockCostDiamonds: 12,
    isUnlockedByDefault: false,
    defaultColor: '#0ea5e9',
    specialAura: '⚡ Tia chớp Grand Tourer',
  },
  {
    id: 'bong_rabbit_r',
    name: 'BÔNG RABBIT R',
    subTitle: 'Thỏ Trắng Phóng Nhanh',
    category: 'mascot_special',
    description:
      'Chiếc xe siêu tốc đáng yêu của bé Bông với đôi tai thỏ lướt gió, gia tốc nhảy vọt thần kỳ sau mỗi khúc cua!',
    baseStats: {
      topSpeed: 84,
      acceleration: 94,
      handling: 86,
      drift: 82,
      nitro: 88,
      braking: 85,
    },
    unlockCostStars: 35,
    unlockCostDiamonds: 15,
    isUnlockedByDefault: false,
    defaultColor: '#f472b6',
    mascotOwner: 'bong',
    specialAura: '🐰 Bước nhảy thỏ siêu tốc',
  },
  {
    id: 'ap_x',
    name: 'AP-X SUPERCAR',
    subTitle: 'Quái Kiệt Đường Đua V-12',
    category: 'supercar',
    description:
      'Thiết kế gầm thấp cắt gió, cánh gió carbon và bộ khuếch tán sau uy lực. Một trong những cỗ máy tốc độ đỉnh cao.',
    baseStats: {
      topSpeed: 92,
      acceleration: 90,
      handling: 85,
      drift: 86,
      nitro: 90,
      braking: 88,
    },
    unlockCostStars: 50,
    unlockCostDiamonds: 20,
    isUnlockedByDefault: false,
    defaultColor: '#eab308',
    specialAura: '✨ Hào quang Siêu Xe Hoàng Kim',
  },
  {
    id: 'ap_e',
    name: 'AP-E CYBER',
    subTitle: 'Electric Lightning Performance',
    category: 'electric',
    description:
      'Động cơ 4 motor điện phản hồi tức thì trong chớp mắt. Khả năng bứt tốc 0-100 km/h không có đối thủ!',
    baseStats: {
      topSpeed: 89,
      acceleration: 98,
      handling: 91,
      drift: 83,
      nitro: 94,
      braking: 92,
    },
    unlockCostStars: 60,
    unlockCostDiamonds: 25,
    isUnlockedByDefault: false,
    defaultColor: '#10b981',
    specialAura: '⚡ Luồng điện Cyber Cyan',
  },
  {
    id: 'ap_hyper',
    name: 'AP-HYPER HYPERION',
    subTitle: 'Siêu Phẩm Hypercar Vượt Giới Hạn',
    category: 'hypercar',
    description:
      'Tuyệt tác công nghệ siêu xe với vận tốc tối đa khủng khiếp, cánh gió thích ứng chủ động và nitro tên lửa hai luồng.',
    baseStats: {
      topSpeed: 97,
      acceleration: 93,
      handling: 89,
      drift: 88,
      nitro: 96,
      braking: 93,
    },
    unlockCostStars: 80,
    unlockCostDiamonds: 35,
    isUnlockedByDefault: false,
    defaultColor: '#8b5cf6',
    specialAura: '🌌 Lốc xoáy Hyperion Tím',
  },
  {
    id: 'lumi_hyper',
    name: 'LUMI HYPER UNICORN',
    subTitle: 'Kỳ Lân Cầu Vồng Vũ Trụ',
    category: 'mascot_special',
    description:
      'Huyền thoại của bé Lumi! Vỏ xe ngọc trai ánh cầu vồng, sừng kỳ lân phát sáng và luồng Nitro 7 màu rực rỡ nhất vương quốc.',
    baseStats: {
      topSpeed: 100,
      acceleration: 99,
      handling: 97,
      drift: 95,
      nitro: 100,
      braking: 98,
    },
    unlockCostStars: 100,
    unlockCostDiamonds: 50,
    isUnlockedByDefault: false,
    defaultColor: '#ffffff',
    mascotOwner: 'lumi',
    specialAura: '🌈 Cầu Vồng Tinh Tú Đa Chiều',
  },
  {
    id: 'yellow_exotic_v12',
    name: 'EXOTIC V12 SUPERCAR',
    subTitle: 'Siêu Xe Hoàng Kim Ý V12',
    category: 'supercar',
    description:
      'Tuyệt tác đường đua màu vàng hoàng kim bóng bẩy, hốc hút gió khí động học sắc sảo và động cơ V12 gầm vang cuồng nhiệt.',
    baseStats: {
      topSpeed: 94,
      acceleration: 91,
      handling: 88,
      drift: 87,
      nitro: 92,
      braking: 89,
    },
    unlockCostStars: 40,
    unlockCostDiamonds: 15,
    isUnlockedByDefault: false,
    defaultColor: '#f59e0b',
    specialAura: '🌟 Hào quang Vàng Kim V12',
  },
  {
    id: 'ford_gt_stripes',
    name: 'FORD GT HERITAGE',
    subTitle: 'Huyền Thoại V8 Sọc Đua Mỹ',
    category: 'supercar',
    description:
      'Biểu tượng tốc độ bất tử với màu sơn vàng hai sọc đua đen chạy dọc thân, thân xe gầm thấp ôm sát mặt đường.',
    baseStats: {
      topSpeed: 95,
      acceleration: 89,
      handling: 86,
      drift: 89,
      nitro: 91,
      braking: 87,
    },
    unlockCostStars: 45,
    unlockCostDiamonds: 18,
    isUnlockedByDefault: false,
    defaultColor: '#eab308',
    specialAura: '🏁 Sọc Đua Huyền Thoại GT',
  },
  {
    id: 'amg_gt3_monster',
    name: 'AMG GT3 MONSTER',
    subTitle: 'Quái Vật Đường Đua Cam Đen',
    category: 'euro_sport',
    description:
      'Thân xe widebody cơ bắp, lưới tản nhiệt dọc dũng mãnh, cánh gió GT khổng lồ cùng pô xả bên hông đầy uy lực!',
    baseStats: {
      topSpeed: 93,
      acceleration: 92,
      handling: 94,
      drift: 90,
      nitro: 89,
      braking: 95,
    },
    unlockCostStars: 55,
    unlockCostDiamonds: 22,
    isUnlockedByDefault: false,
    defaultColor: '#f97316',
    specialAura: '🔥 Sức Mạnh Quái Vật AMG GT3',
  },
  {
    id: 'solus_hyper_proto',
    name: 'SOLUS HYPER-PROTO',
    subTitle: 'Phi Thuyền Tương Lai F1',
    category: 'hypercar',
    description:
      'Siêu phẩm Hypercar nguyên mẫu tương lai với màu trắng phối xanh ngọc, buồng lái kính phi thuyền kín và lực ép vòm khí tối đa.',
    baseStats: {
      topSpeed: 99,
      acceleration: 97,
      handling: 96,
      drift: 93,
      nitro: 98,
      braking: 96,
    },
    unlockCostStars: 75,
    unlockCostDiamonds: 30,
    isUnlockedByDefault: false,
    defaultColor: '#f8fafc',
    specialAura: '🌌 Khí Động Học Solus Tương Lai',
  },
  {
    id: 'miata_roadster',
    name: 'MIATA MX-5 ROADSTER',
    subTitle: 'Xe Thể Thao Mui Trần Bạc',
    category: 'sport',
    description:
      'Mui trần lãng mạn nhẹ nhàng, trọng lượng siêu nhẹ giúp bẻ lái cực nhạy và ôm cua góc hẹp mượt mà không đối thủ.',
    baseStats: {
      topSpeed: 81,
      acceleration: 87,
      handling: 96,
      drift: 94,
      nitro: 82,
      braking: 91,
    },
    unlockCostStars: 25,
    unlockCostDiamonds: 10,
    isUnlockedByDefault: false,
    defaultColor: '#94a3b8',
    specialAura: '🍃 Gió Mui Trần Lướt Phố',
  },
  {
    id: 'nissan_370z_tuner',
    name: 'NISSAN 370Z FAIRLADY',
    subTitle: 'JDM Street Coupe Vàng Sọc Capo',
    category: 'jdm',
    description:
      'Chiếc xe thể thao hai cửa kiêu hãnh của văn hóa JDM với động cơ V6 linh hoạt, nắp capo sơn sọc đen thể thao rực rỡ.',
    baseStats: {
      topSpeed: 85,
      acceleration: 86,
      handling: 91,
      drift: 95,
      nitro: 85,
      braking: 88,
    },
    unlockCostStars: 32,
    unlockCostDiamonds: 12,
    isUnlockedByDefault: false,
    defaultColor: '#eab308',
    specialAura: '🔰 Vệt Drift JDM Fairlady',
  },
];

export const PAINT_PALETTES = [
  { name: 'Đỏ Đua Sport', hex: '#ef4444' },
  { name: 'Xanh Neon Cyan', hex: '#06b6d4' },
  { name: 'Vàng Hoàng Kim', hex: '#eab308' },
  { name: 'Tím Thiên Hà (Galaxy)', hex: '#8b5cf6' },
  { name: 'Hồng Ngọc Trai (Pink Pearl)', hex: '#f472b6' },
  { name: 'Xanh Lá Mint', hex: '#10b981' },
  { name: 'Capybara Nâu Ấm', hex: '#c2884a' },
  { name: 'Trắng Ngọc Tuyết', hex: '#f8fafc' },
  { name: 'Đen Huyền Bí Phantom', hex: '#18181b' },
  { name: 'Cầu Vồng Pastel (Rainbow)', hex: '#a855f7' },
];

export const WHEEL_STYLES: { id: CarCustomization['wheelStyle']; name: string; icon: string }[] = [
  { id: 'sport', name: '5-Chấu Thể Thao', icon: '🛞' },
  { id: 'star', name: 'Ngôi Sao Đua', icon: '⭐' },
  { id: 'aero', name: 'Aero Khí Động Học', icon: '🌀' },
  { id: 'gold_chrome', name: 'Mạ Vàng Chrome', icon: '✨' },
];

export const SPOILER_STYLES: { id: CarCustomization['spoilerStyle']; name: string }[] = [
  { id: 'stock', name: 'Tiêu chuẩn (Stock)' },
  { id: 'sport_wing', name: 'Cánh gió Sport' },
  { id: 'gt_wing', name: 'Cánh gió Đua GT' },
  { id: 'neon_wing', name: 'Cánh gió Neon LED' },
];

export const NEON_UNDERGLOW_OPTIONS: { id: CarCustomization['neonUnderglow']; name: string; color: string }[] = [
  { id: 'none', name: 'Tắt đèn gầm', color: 'transparent' },
  { id: 'cyan', name: 'Cyan Băng Giá', color: '#06b6d4' },
  { id: 'purple', name: 'Tím Neon Cyber', color: '#a855f7' },
  { id: 'pink', name: 'Hồng Kẹo Ngọt', color: '#f43f5e' },
  { id: 'lime', name: 'Xanh Lime Năng Động', color: '#84cc16' },
  { id: 'gold', name: 'Vàng Ánh Kim', color: '#eab308' },
  { id: 'rainbow', name: 'Cầu Vồng Lấp Lánh', color: '#ec4899' },
];

export const DEFAULT_CUSTOMIZATION: CarCustomization = {
  paintColor: '#ef4444',
  paintFinish: 'metallic',
  wheelStyle: 'sport',
  wheelColor: '#1e293b',
  spoilerStyle: 'sport_wing',
  neonUnderglow: 'cyan',
  windowTint: 'smoke',
  decal: 'stripes',
};

export const DEFAULT_UPGRADES: CarUpgrades = {
  engine: 1,
  acceleration: 1,
  handling: 1,
  nitro: 1,
  brakes: 1,
};

const RACING_SAVE_KEY = 'bara_speed_racing_profile_v1';

export function getInitialRaceProfile(): PlayerRaceProfile {
  return {
    unlockedCars: [
      'bara_gt', 'capybara_parade_3d', 'ap_r1', 'canis_mesa_3d', 'v12_sv_3d', 'roadster_883_3d',
      'vespa_studio_3d', 's14_sport_3d', 'rescue_truck_hauler_3d', 'xedap_city_3d',
      'police_car_3d', 'police_motorcycle_3d', 'ambulance_3d', 'tank_racer_3d', 'helicopter_racer_3d',
      'dodge_wc51_3d', 'spider_racer_3d', 'robot19_racer_3d', 'robot4_racer_3d', 'prime1_racer_3d',
      'ironman_mark3_racer_3d', 'zora_nao_racer_3d', 'mark6_racer_3d', 'hulk_racer_3d', 'captain_racer_3d', 'knut_racer_3d',
      'us_soldier_racer_3d', 'human_racer_3d', 'drag_driver_racer_3d',
    ],
    selectedCarId: 'bara_gt',
    carCustomizations: {
      bara_gt: {
        ...DEFAULT_CUSTOMIZATION,
        paintColor: '#c2884a',
        neonUnderglow: 'gold',
      },
      capybara_parade_3d: {
        ...DEFAULT_CUSTOMIZATION,
        paintColor: '#b78652',
        paintFinish: 'glossy',
        wheelStyle: 'sport',
        spoilerStyle: 'stock',
        neonUnderglow: 'gold',
        decal: 'none',
      },
      ap_r1: {
        ...DEFAULT_CUSTOMIZATION,
        paintColor: '#ef4444',
        neonUnderglow: 'cyan',
      },
    },
    carUpgrades: {
      bara_gt: { ...DEFAULT_UPGRADES },
      capybara_parade_3d: { ...DEFAULT_UPGRADES },
      ap_r1: { ...DEFAULT_UPGRADES },
    },
    unlockedTracks: ['neon_city', 'coastal_highway', 'mountain_pass'],
    bestLapTimes: {},
    careerProgress: 0,
    totalDriftScore: 0,
    totalNitroUsed: 0,
    racesWon: 0,
  };
}

export function loadRaceProfile(): PlayerRaceProfile {
  try {
    const raw = localStorage.getItem(RACING_SAVE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      const initial = getInitialRaceProfile();
      const mergedUnlockedCars = Array.from(new Set([
        ...(initial.unlockedCars || []),
        ...(parsed.unlockedCars || []),
        'canis_mesa_3d',
        'v12_sv_3d',
        'roadster_883_3d',
        'vespa_studio_3d',
        's14_sport_3d',
        'rescue_truck_hauler_3d',
        'xedap_city_3d',
        'capybara_parade_3d',
        'police_car_3d',
        'police_motorcycle_3d',
        'ambulance_3d',
        'tank_racer_3d',
        'helicopter_racer_3d',
        'dodge_wc51_3d',
        'spider_racer_3d',
        'robot19_racer_3d',
        'robot4_racer_3d',
        'prime1_racer_3d',
        'ironman_mark3_racer_3d',
        'zora_nao_racer_3d',
        'mark6_racer_3d',
        'hulk_racer_3d',
        'captain_racer_3d',
        'knut_racer_3d',
        'us_soldier_racer_3d',
        'human_racer_3d',
        'drag_driver_racer_3d',
      ])) as CarModelId[];
      return {
        ...initial,
        ...parsed,
        unlockedCars: mergedUnlockedCars,
        carCustomizations: { ...initial.carCustomizations, ...(parsed.carCustomizations || {}) },
        carUpgrades: { ...initial.carUpgrades, ...(parsed.carUpgrades || {}) },
        bestLapTimes: { ...initial.bestLapTimes, ...(parsed.bestLapTimes || {}) },
      };
    }
  } catch (e) {
    // Fallback
  }
  return getInitialRaceProfile();
}

export function saveRaceProfile(profile: PlayerRaceProfile) {
  try {
    localStorage.setItem(RACING_SAVE_KEY, JSON.stringify(profile));
  } catch (e) {}
}

export function calculateUpgradedStats(car: CarConfig, upgrades?: CarUpgrades): CarStats {
  const up = upgrades || DEFAULT_UPGRADES;
  const statBoost = (level: number) => (level - 1) * 3.5;

  return {
    topSpeed: Math.min(100, Math.round(car.baseStats.topSpeed + statBoost(up.engine))),
    acceleration: Math.min(100, Math.round(car.baseStats.acceleration + statBoost(up.acceleration))),
    handling: Math.min(100, Math.round(car.baseStats.handling + statBoost(up.handling))),
    drift: Math.min(100, Math.round(car.baseStats.drift + statBoost(up.handling) * 0.5)),
    nitro: Math.min(100, Math.round(car.baseStats.nitro + statBoost(up.nitro))),
    braking: Math.min(100, Math.round(car.baseStats.braking + statBoost(up.brakes))),
  };
}
